services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "8000:80"  # Map Nginx to host port 8000
    volumes:
      - ./:/var/www/html
      - ./nginx-config/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount custom Nginx config
    networks:
      - app_network

  php:
    build:
      context: ./
    restart: unless-stopped
    init: true
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge
